name: soccer_assistant_coach
description: Flutter app with theme, edit screens, lineup, stats, CSV import/export
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  drift: ^2.18.0
  drift_sqflite: ^2.0.1
  path_provider: ^2.1.4
  json_annotation: ^4.9.0
  shared_preferences: ^2.3.2
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  image_picker: ^1.1.2
  vibration: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  drift_dev: ^2.18.0
  json_serializable: ^6.9.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/

flutter_icons:
  android: true
  ios: true
  image_path: "soccer-assistant-coach.png"
  adaptive_icon_background: "#0A0A0A"
  adaptive_icon_foreground: "soccer-assistant-coach.png"
