name: soccer_assistant_coach
description: Flutter app with theme, edit screens, lineup, stats, CSV import/export
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  go_router: ^16.2.5
  drift: ^2.18.0
  drift_sqflite: ^2.0.1
  path_provider: ^2.1.5
  json_annotation: ^4.9.0
  shared_preferences: ^2.3.2
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  image_picker: ^1.1.3
  vibration: ^3.1.4
  flex_color_picker: ^3.7.1
  path: ^1.9.1
  file_picker: ^10.3.3
  share_plus: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.7.1 # Incompatible upgrade blocked by analyzer/test_api graph
  drift_dev: ^2.18.0
  json_serializable: ^6.11.1
  # Upgraded for Riverpod v3 compatibility (analyzer/build graph)
  flutter_launcher_icons: ^0.14.4

dependency_overrides:
  device_info_plus: ^12.1.0
  characters: ^1.4.1
  material_color_utilities: ^0.13.0
  meta: ^1.17.0


flutter:
  uses-material-design: true
  assets:
    - assets/sounds/

flutter_icons:
  android: true
  ios: true
  image_path: "soccer-assistant-coach.png"
  adaptive_icon_background: "#0A0A0A"
  adaptive_icon_foreground: "soccer-assistant-coach.png"
